[project]
name = "meu-agente-cli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Bruno Roma", email = "bruuno@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "croniter>=6.2.4",
    "cryptography>=50.0.0",
    "dotenv>=0.9.9",
    "feedparser>=6.0.14",
    "httpx>=0.28.1",
    "openpyxl>=3.1.2",
    "psycopg[binary]>=3.3.4",
    "pyaudio>=0.2.14",
    "pypdf>=4.0.1",
    "pyTelegramBotAPI>=4.26.0",
    "python-docx>=1.1.0",
    "rich>=15.0.0",
    "speechrecognition>=3.17.0",
    "tqdm>=4.70.0",
    "yfinance>=1.5.2",
]

[project.scripts]
meu-agente-cli = "meu_agente_cli:main"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"
