-- ==============================================================================
-- Migracao dos Lancamentos do Cartao Itau Fabiana para o Servidor de Producao
-- Total de lancamentos de cartao: 110
-- ==============================================================================

BEGIN;

-- 1. Cadastra ou atualiza o cartao na tabela credit_cards
INSERT INTO credit_cards (name, bank, due_day, closing_day, user_name, active)
VALUES ('Itaú Fabiana', 'Itaú', 13, 2, 'fabiana', TRUE)
ON CONFLICT (name) DO UPDATE
SET bank = EXCLUDED.bank,
    due_day = EXCLUDED.due_day,
    closing_day = EXCLUDED.closing_day,
    user_name = EXCLUDED.user_name,
    active = EXCLUDED.active;

-- 2. Insere os lancamentos vinculando dinamicamente ao card_id correspondente
DO $$
DECLARE
    v_card_id INT;
BEGIN
    SELECT id INTO v_card_id FROM credit_cards WHERE name = 'Itaú Fabiana' LIMIT 1;
    IF v_card_id IS NULL THEN
        RAISE EXCEPTION 'Cartao Itau Fabiana nao encontrado na tabela credit_cards!';
    END IF;

    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 272.00, '[Itaú Fabiana 1/9] itaushop', '2026-09-10', '2026-10-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 1/9] itaushop' AND due_date = '2026-10-13' AND amount = 272.00 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 272.00, '[Itaú Fabiana 2/9] itaushop', '2026-09-10', '2026-11-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 2/9] itaushop' AND due_date = '2026-11-13' AND amount = 272.00 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 272.00, '[Itaú Fabiana 3/9] itaushop', '2026-09-10', '2026-12-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 3/9] itaushop' AND due_date = '2026-12-13' AND amount = 272.00 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 272.00, '[Itaú Fabiana 4/9] itaushop', '2026-09-10', '2027-01-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 4/9] itaushop' AND due_date = '2027-01-13' AND amount = 272.00 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 272.00, '[Itaú Fabiana 5/9] itaushop', '2026-09-10', '2027-02-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 5/9] itaushop' AND due_date = '2027-02-13' AND amount = 272.00 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 272.00, '[Itaú Fabiana 6/9] itaushop', '2026-09-10', '2027-03-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 6/9] itaushop' AND due_date = '2027-03-13' AND amount = 272.00 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 272.00, '[Itaú Fabiana 7/9] itaushop', '2026-09-10', '2027-04-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 7/9] itaushop' AND due_date = '2027-04-13' AND amount = 272.00 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 272.00, '[Itaú Fabiana 8/9] itaushop', '2026-09-10', '2027-05-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 8/9] itaushop' AND due_date = '2027-05-13' AND amount = 272.00 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 272.00, '[Itaú Fabiana 9/9] itaushop', '2026-09-10', '2027-06-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 9/9] itaushop' AND due_date = '2027-06-13' AND amount = 272.00 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 124.00, '[Itaú Fabiana 1/1] Oculos', '2026-09-10', '2026-10-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 1/1] Oculos' AND due_date = '2026-10-13' AND amount = 124.00 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 71.03, '[Itaú Fabiana 1/1] Rihappy', '2026-09-10', '2026-10-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 1/1] Rihappy' AND due_date = '2026-10-13' AND amount = 71.03 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 127.98, '[Itaú Fabiana 1/1] HS Modas', '2026-09-10', '2026-10-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 1/1] HS Modas' AND due_date = '2026-10-13' AND amount = 127.98 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 37.71, '[Itaú Fabiana 1/2] editora sesi', '2026-09-10', '2026-10-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 1/2] editora sesi' AND due_date = '2026-10-13' AND amount = 37.71 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 37.71, '[Itaú Fabiana 2/2] editora sesi', '2026-09-10', '2026-11-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 2/2] editora sesi' AND due_date = '2026-11-13' AND amount = 37.71 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 49.31, '[Itaú Fabiana 1/2] editora sesi 2', '2029-09-10', '2029-10-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 1/2] editora sesi 2' AND due_date = '2029-10-13' AND amount = 49.31 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 49.31, '[Itaú Fabiana 2/2] editora sesi 2', '2029-09-10', '2029-11-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 2/2] editora sesi 2' AND due_date = '2029-11-13' AND amount = 49.31 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 49.31, '[Itaú Fabiana 1/2] editora sesi 2', '2026-09-10', '2026-10-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 1/2] editora sesi 2' AND due_date = '2026-10-13' AND amount = 49.31 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 49.31, '[Itaú Fabiana 2/2] editora sesi 2', '2026-09-10', '2026-11-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 2/2] editora sesi 2' AND due_date = '2026-11-13' AND amount = 49.31 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 81.67, '[Itaú Fabiana 1/4] Amazon', '2026-09-10', '2026-10-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 1/4] Amazon' AND due_date = '2026-10-13' AND amount = 81.67 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 81.67, '[Itaú Fabiana 2/4] Amazon', '2026-09-10', '2026-11-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 2/4] Amazon' AND due_date = '2026-11-13' AND amount = 81.67 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 81.67, '[Itaú Fabiana 3/4] Amazon', '2026-09-10', '2026-12-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 3/4] Amazon' AND due_date = '2026-12-13' AND amount = 81.67 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 81.67, '[Itaú Fabiana 4/4] Amazon', '2026-09-10', '2027-01-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 4/4] Amazon' AND due_date = '2027-01-13' AND amount = 81.67 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 142.65, '[Itaú Fabiana 1/6] Amazon MKT', '2026-09-10', '2026-10-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 1/6] Amazon MKT' AND due_date = '2026-10-13' AND amount = 142.65 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 142.65, '[Itaú Fabiana 2/6] Amazon MKT', '2026-09-10', '2026-11-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 2/6] Amazon MKT' AND due_date = '2026-11-13' AND amount = 142.65 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 142.65, '[Itaú Fabiana 3/6] Amazon MKT', '2026-09-10', '2026-12-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 3/6] Amazon MKT' AND due_date = '2026-12-13' AND amount = 142.65 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 142.65, '[Itaú Fabiana 4/6] Amazon MKT', '2026-09-10', '2027-01-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 4/6] Amazon MKT' AND due_date = '2027-01-13' AND amount = 142.65 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 142.65, '[Itaú Fabiana 5/6] Amazon MKT', '2026-09-10', '2027-02-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 5/6] Amazon MKT' AND due_date = '2027-02-13' AND amount = 142.65 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 142.65, '[Itaú Fabiana 6/6] Amazon MKT', '2026-09-10', '2027-03-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 6/6] Amazon MKT' AND due_date = '2027-03-13' AND amount = 142.65 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 98.35, '[Itaú Fabiana 1/1] red beach', '2026-09-10', '2026-10-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 1/1] red beach' AND due_date = '2026-10-13' AND amount = 98.35 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 37.30, '[Itaú Fabiana 1/1] CONSMAT FOR', '2026-09-10', '2026-10-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 1/1] CONSMAT FOR' AND due_date = '2026-10-13' AND amount = 37.30 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 101.30, '[Itaú Fabiana 1/3] LEROY MERLIN', '2026-09-10', '2026-10-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 1/3] LEROY MERLIN' AND due_date = '2026-10-13' AND amount = 101.30 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 101.30, '[Itaú Fabiana 2/3] LEROY MERLIN', '2026-09-10', '2026-11-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 2/3] LEROY MERLIN' AND due_date = '2026-11-13' AND amount = 101.30 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 101.30, '[Itaú Fabiana 3/3] LEROY MERLIN', '2026-09-10', '2026-12-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 3/3] LEROY MERLIN' AND due_date = '2026-12-13' AND amount = 101.30 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 52.86, '[Itaú Fabiana 1/4] PERLATTO', '2026-09-10', '2026-10-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 1/4] PERLATTO' AND due_date = '2026-10-13' AND amount = 52.86 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 52.86, '[Itaú Fabiana 2/4] PERLATTO', '2026-09-10', '2026-11-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 2/4] PERLATTO' AND due_date = '2026-11-13' AND amount = 52.86 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 52.86, '[Itaú Fabiana 3/4] PERLATTO', '2026-09-10', '2026-12-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 3/4] PERLATTO' AND due_date = '2026-12-13' AND amount = 52.86 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 52.86, '[Itaú Fabiana 4/4] PERLATTO', '2026-09-10', '2027-01-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 4/4] PERLATTO' AND due_date = '2027-01-13' AND amount = 52.86 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 57.18, '[Itaú Fabiana 1/4] PERLATTO 2', '2026-09-10', '2026-10-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 1/4] PERLATTO 2' AND due_date = '2026-10-13' AND amount = 57.18 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 57.18, '[Itaú Fabiana 2/4] PERLATTO 2', '2026-09-10', '2026-11-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 2/4] PERLATTO 2' AND due_date = '2026-11-13' AND amount = 57.18 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 57.18, '[Itaú Fabiana 3/4] PERLATTO 2', '2026-09-10', '2026-12-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 3/4] PERLATTO 2' AND due_date = '2026-12-13' AND amount = 57.18 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 57.18, '[Itaú Fabiana 4/4] PERLATTO 2', '2026-09-10', '2027-01-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 4/4] PERLATTO 2' AND due_date = '2027-01-13' AND amount = 57.18 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 356.80, '[Itaú Fabiana 1/8] TAUA HOTEL E', '2026-09-10', '2026-10-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 1/8] TAUA HOTEL E' AND due_date = '2026-10-13' AND amount = 356.80 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 356.80, '[Itaú Fabiana 2/8] TAUA HOTEL E', '2026-09-10', '2026-11-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 2/8] TAUA HOTEL E' AND due_date = '2026-11-13' AND amount = 356.80 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 356.80, '[Itaú Fabiana 3/8] TAUA HOTEL E', '2026-09-10', '2026-12-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 3/8] TAUA HOTEL E' AND due_date = '2026-12-13' AND amount = 356.80 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 356.80, '[Itaú Fabiana 4/8] TAUA HOTEL E', '2026-09-10', '2027-01-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 4/8] TAUA HOTEL E' AND due_date = '2027-01-13' AND amount = 356.80 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 356.80, '[Itaú Fabiana 5/8] TAUA HOTEL E', '2026-09-10', '2027-02-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 5/8] TAUA HOTEL E' AND due_date = '2027-02-13' AND amount = 356.80 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 356.80, '[Itaú Fabiana 6/8] TAUA HOTEL E', '2026-09-10', '2027-03-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 6/8] TAUA HOTEL E' AND due_date = '2027-03-13' AND amount = 356.80 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 356.80, '[Itaú Fabiana 7/8] TAUA HOTEL E', '2026-09-10', '2027-04-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 7/8] TAUA HOTEL E' AND due_date = '2027-04-13' AND amount = 356.80 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 356.80, '[Itaú Fabiana 8/8] TAUA HOTEL E', '2026-09-10', '2027-05-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 8/8] TAUA HOTEL E' AND due_date = '2027-05-13' AND amount = 356.80 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 312.20, '[Itaú Fabiana 1/8] TAUA HOTEL', '2026-09-10', '2026-10-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 1/8] TAUA HOTEL' AND due_date = '2026-10-13' AND amount = 312.20 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 312.20, '[Itaú Fabiana 2/8] TAUA HOTEL', '2026-09-10', '2026-11-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 2/8] TAUA HOTEL' AND due_date = '2026-11-13' AND amount = 312.20 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 312.20, '[Itaú Fabiana 3/8] TAUA HOTEL', '2026-09-10', '2026-12-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 3/8] TAUA HOTEL' AND due_date = '2026-12-13' AND amount = 312.20 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 312.20, '[Itaú Fabiana 4/8] TAUA HOTEL', '2026-09-10', '2027-01-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 4/8] TAUA HOTEL' AND due_date = '2027-01-13' AND amount = 312.20 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 312.20, '[Itaú Fabiana 5/8] TAUA HOTEL', '2026-09-10', '2027-02-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 5/8] TAUA HOTEL' AND due_date = '2027-02-13' AND amount = 312.20 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 312.20, '[Itaú Fabiana 6/8] TAUA HOTEL', '2026-09-10', '2027-03-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 6/8] TAUA HOTEL' AND due_date = '2027-03-13' AND amount = 312.20 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 312.20, '[Itaú Fabiana 7/8] TAUA HOTEL', '2026-09-10', '2027-04-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 7/8] TAUA HOTEL' AND due_date = '2027-04-13' AND amount = 312.20 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 312.20, '[Itaú Fabiana 8/8] TAUA HOTEL', '2026-09-10', '2027-05-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 8/8] TAUA HOTEL' AND due_date = '2027-05-13' AND amount = 312.20 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 107.10, '[Itaú Fabiana 1/2] NAT*Natura Pa', '2026-09-10', '2026-10-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 1/2] NAT*Natura Pa' AND due_date = '2026-10-13' AND amount = 107.10 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 107.10, '[Itaú Fabiana 2/2] NAT*Natura Pa', '2026-09-10', '2026-11-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 2/2] NAT*Natura Pa' AND due_date = '2026-11-13' AND amount = 107.10 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 52.06, '[Itaú Fabiana 1/3] PERLATTO FULL', '2026-09-10', '2026-10-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 1/3] PERLATTO FULL' AND due_date = '2026-10-13' AND amount = 52.06 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 52.06, '[Itaú Fabiana 2/3] PERLATTO FULL', '2026-09-10', '2026-11-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 2/3] PERLATTO FULL' AND due_date = '2026-11-13' AND amount = 52.06 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 52.06, '[Itaú Fabiana 3/3] PERLATTO FULL', '2026-09-10', '2026-12-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 3/3] PERLATTO FULL' AND due_date = '2026-12-13' AND amount = 52.06 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 267.10, '[Itaú Fabiana 1/1] NAT*Natura', '2026-09-10', '2026-10-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 1/1] NAT*Natura' AND due_date = '2026-10-13' AND amount = 267.10 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 290.00, '[Itaú Fabiana 1/11] Fashion Photo', '2026-09-10', '2026-10-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 1/11] Fashion Photo' AND due_date = '2026-10-13' AND amount = 290.00 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 290.00, '[Itaú Fabiana 2/11] Fashion Photo', '2026-09-10', '2026-11-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 2/11] Fashion Photo' AND due_date = '2026-11-13' AND amount = 290.00 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 290.00, '[Itaú Fabiana 3/11] Fashion Photo', '2026-09-10', '2026-12-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 3/11] Fashion Photo' AND due_date = '2026-12-13' AND amount = 290.00 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 290.00, '[Itaú Fabiana 4/11] Fashion Photo', '2026-09-10', '2027-01-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 4/11] Fashion Photo' AND due_date = '2027-01-13' AND amount = 290.00 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 290.00, '[Itaú Fabiana 5/11] Fashion Photo', '2026-09-10', '2027-02-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 5/11] Fashion Photo' AND due_date = '2027-02-13' AND amount = 290.00 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 290.00, '[Itaú Fabiana 6/11] Fashion Photo', '2026-09-10', '2027-03-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 6/11] Fashion Photo' AND due_date = '2027-03-13' AND amount = 290.00 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 290.00, '[Itaú Fabiana 7/11] Fashion Photo', '2026-09-10', '2027-04-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 7/11] Fashion Photo' AND due_date = '2027-04-13' AND amount = 290.00 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 290.00, '[Itaú Fabiana 8/11] Fashion Photo', '2026-09-10', '2027-05-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 8/11] Fashion Photo' AND due_date = '2027-05-13' AND amount = 290.00 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 290.00, '[Itaú Fabiana 9/11] Fashion Photo', '2026-09-10', '2027-06-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 9/11] Fashion Photo' AND due_date = '2027-06-13' AND amount = 290.00 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 290.00, '[Itaú Fabiana 10/11] Fashion Photo', '2026-09-10', '2027-07-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 10/11] Fashion Photo' AND due_date = '2027-07-13' AND amount = 290.00 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 290.00, '[Itaú Fabiana 11/11] Fashion Photo', '2026-09-10', '2027-08-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 11/11] Fashion Photo' AND due_date = '2027-08-13' AND amount = 290.00 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 133.41, '[Itaú Fabiana 1/6] MAGALU', '2026-09-10', '2026-10-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 1/6] MAGALU' AND due_date = '2026-10-13' AND amount = 133.41 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 133.41, '[Itaú Fabiana 2/6] MAGALU', '2026-09-10', '2026-11-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 2/6] MAGALU' AND due_date = '2026-11-13' AND amount = 133.41 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 133.41, '[Itaú Fabiana 3/6] MAGALU', '2026-09-10', '2026-12-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 3/6] MAGALU' AND due_date = '2026-12-13' AND amount = 133.41 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 133.41, '[Itaú Fabiana 4/6] MAGALU', '2026-09-10', '2027-01-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 4/6] MAGALU' AND due_date = '2027-01-13' AND amount = 133.41 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 133.41, '[Itaú Fabiana 5/6] MAGALU', '2026-09-10', '2027-02-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 5/6] MAGALU' AND due_date = '2027-02-13' AND amount = 133.41 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 133.41, '[Itaú Fabiana 6/6] MAGALU', '2026-09-10', '2027-03-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 6/6] MAGALU' AND due_date = '2027-03-13' AND amount = 133.41 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 119.11, '[Itaú Fabiana 1/1] Andorinha', '2026-09-10', '2026-10-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 1/1] Andorinha' AND due_date = '2026-10-13' AND amount = 119.11 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 100.00, '[Itaú Fabiana 1/1] Combustivel Sofiserv', '2026-09-04', '2026-10-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 1/1] Combustivel Sofiserv' AND due_date = '2026-10-13' AND amount = 100.00 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 19.00, '[Itaú Fabiana 1/1] jovipel', '2026-09-05', '2026-10-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 1/1] jovipel' AND due_date = '2026-10-13' AND amount = 19.00 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 36.00, '[Itaú Fabiana 1/1] REGA CAFESAO PAULOBRA', '2026-09-05', '2026-10-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 1/1] REGA CAFESAO PAULOBRA' AND due_date = '2026-10-13' AND amount = 36.00 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 9.00, '[Itaú Fabiana 1/1] REGA CAFESAO PAULOBRA', '2026-09-05', '2026-10-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 1/1] REGA CAFESAO PAULOBRA' AND due_date = '2026-10-13' AND amount = 9.00 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 12.00, '[Itaú Fabiana 1/1] REGA CAFESAO PAULOBRA', '2026-09-05', '2026-10-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 1/1] REGA CAFESAO PAULOBRA' AND due_date = '2026-10-13' AND amount = 12.00 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 45.00, '[Itaú Fabiana 1/1] G1EstacionamentosSAO PA', '2026-09-05', '2026-10-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 1/1] G1EstacionamentosSAO PA' AND due_date = '2026-10-13' AND amount = 45.00 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 36.95, '[Itaú Fabiana 1/1] AKITEM ABPSAO PAULOBRA', '2026-09-07', '2026-10-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 1/1] AKITEM ABPSAO PAULOBRA' AND due_date = '2026-10-13' AND amount = 36.95 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 190.28, '[Itaú Fabiana 1/3] NAT*Natura Pag', '2026-09-12', '2026-10-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 1/3] NAT*Natura Pag' AND due_date = '2026-10-13' AND amount = 190.28 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 190.28, '[Itaú Fabiana 2/3] NAT*Natura Pag', '2026-09-12', '2026-11-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 2/3] NAT*Natura Pag' AND due_date = '2026-11-13' AND amount = 190.28 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 190.28, '[Itaú Fabiana 3/3] NAT*Natura Pag', '2026-09-12', '2026-12-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 3/3] NAT*Natura Pag' AND due_date = '2026-12-13' AND amount = 190.28 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 100.00, '[Itaú Fabiana 1/1] SOFISERV AUTO POSTOSAO', '2026-09-12', '2026-10-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 1/1] SOFISERV AUTO POSTOSAO' AND due_date = '2026-10-13' AND amount = 100.00 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 170.42, '[Itaú Fabiana 1/1] MERCADOLIVRE*MERCADOLIO', '2026-09-17', '2026-10-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 1/1] MERCADOLIVRE*MERCADOLIO' AND due_date = '2026-10-13' AND amount = 170.42 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 116.92, '[Itaú Fabiana 1/1] ANDORINHA HIPERSAO PAUL', '2026-09-17', '2026-10-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 1/1] ANDORINHA HIPERSAO PAUL' AND due_date = '2026-10-13' AND amount = 116.92 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 10.00, '[Itaú Fabiana 1/1] MarmitariaFitnesSAO PAU', '2026-09-17', '2026-10-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 1/1] MarmitariaFitnesSAO PAU' AND due_date = '2026-10-13' AND amount = 10.00 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 25.79, '[Itaú Fabiana 1/1] PANIFICADORA LENILCE LS', '2026-09-18', '2026-10-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 1/1] PANIFICADORA LENILCE LS' AND due_date = '2026-10-13' AND amount = 25.79 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 20.00, '[Itaú Fabiana 1/1] BluGestaoESAO PAULOBRA', '2026-09-18', '2026-10-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 1/1] BluGestaoESAO PAULOBRA' AND due_date = '2026-10-13' AND amount = 20.00 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 35.00, '[Itaú Fabiana 1/1] CMC PARKING ADMINISTRAS', '2026-09-19', '2026-10-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 1/1] CMC PARKING ADMINISTRAS' AND due_date = '2026-10-13' AND amount = 35.00 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 100.00, '[Itaú Fabiana 1/1] AUTO POSTO NOVA MARAJOB', '2026-09-21', '2026-10-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 1/1] AUTO POSTO NOVA MARAJOB' AND due_date = '2026-10-13' AND amount = 100.00 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 55.98, '[Itaú Fabiana 1/1] Padaria', '2026-09-21', '2026-10-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 1/1] Padaria' AND due_date = '2026-10-13' AND amount = 55.98 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 256.00, '[Itaú Fabiana 1/1] HDI SEGUROS SASao Paulo', '2026-09-21', '2026-10-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 1/1] HDI SEGUROS SASao Paulo' AND due_date = '2026-10-13' AND amount = 256.00 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 97.91, '[Itaú Fabiana 1/2] ANDORINHA HIPE', '2026-09-22', '2026-10-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 1/2] ANDORINHA HIPE' AND due_date = '2026-10-13' AND amount = 97.91 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 97.91, '[Itaú Fabiana 2/2] ANDORINHA HIPE', '2026-09-22', '2026-11-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 2/2] ANDORINHA HIPE' AND due_date = '2026-11-13' AND amount = 97.91 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Alimentação', 28.45, '[Itaú Fabiana 1/1] PANIFICADORA LENILCE LS', '2026-09-24', '2026-10-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 1/1] PANIFICADORA LENILCE LS' AND due_date = '2026-10-13' AND amount = 28.45 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 43.52, '[Itaú Fabiana 1/1] PANIFICADORA LENILCE LS', '2026-09-25', '2026-10-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 1/1] PANIFICADORA LENILCE LS' AND due_date = '2026-10-13' AND amount = 43.52 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 28.00, '[Itaú Fabiana 1/1] MR2 PARKING ESTACIONABA', '2026-09-25', '2026-10-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 1/1] MR2 PARKING ESTACIONABA' AND due_date = '2026-10-13' AND amount = 28.00 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 19.99, '[Itaú Fabiana 1/1] Mercado Livre', '2026-09-25', '2026-10-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 1/1] Mercado Livre' AND due_date = '2026-10-13' AND amount = 19.99 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 100.00, '[Itaú Fabiana 1/1] SOFISERV AUTO POSTO LSA', '2026-09-29', '2026-10-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 1/1] SOFISERV AUTO POSTO LSA' AND due_date = '2026-10-13' AND amount = 100.00 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 39.86, '[Itaú Fabiana 1/1] PEDRA BRANCA 0726SAO PA', '2026-09-30', '2026-10-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 1/1] PEDRA BRANCA 0726SAO PA' AND due_date = '2026-10-13' AND amount = 39.86 AND user_name = 'fabiana');
    INSERT INTO financial_records (type, category, amount, description, date, due_date, active, nature, card_name, is_paid, payment_date, user_name, card_id) SELECT 'despesa', 'Outros', 121.35, '[Itaú Fabiana 1/1] Droga Raia', '2026-10-01', '2026-10-13', TRUE, 'card_purchase', 'Itaú Fabiana', FALSE, NULL, 'fabiana', v_card_id WHERE NOT EXISTS (SELECT 1 FROM financial_records WHERE description = '[Itaú Fabiana 1/1] Droga Raia' AND due_date = '2026-10-13' AND amount = 121.35 AND user_name = 'fabiana');
END $$;

COMMIT;
